# Use root/example as user/password credentials
configs:
  system_config:
    file: ./config.json
  
# volumes:
#   smart-bus-volume:
#   driver: local 
#   driver_opts: 
#     o: 
#       bind type: none
#       device: /path/to/files/on/host


networks:
  smart-bus-system-network:
    driver: bridge
    ipam:
      config:
        - subnet: 20.0.0.0/8


services:

  sensors:
    build: ./sensors
    volumes:
      - ./config.json:/config.json
    environment:
      - IOT_USERNAME=${IOT_USERNAME}
      - IOT_PASSWORD=${IOT_PASSWORD}
    container_name: smart-bus-system-sensors
    networks:
      smart-bus-system-network:
        ipv4_address: 20.0.0.10

  mosquitto:
    container_name: smart-bus-system-mosquitto
    # image: giacomix02/iot_mosquitto:v1
    build:
      context: ./mosquitto
      args:
        - IOT_USERNAME=${IOT_USERNAME}
        - IOT_PASSWORD=${IOT_PASSWORD}
    environment:
      - IOT_USERNAME=${IOT_USERNAME}
      - IOT_PASSWORD=${IOT_PASSWORD}
    volumes:
    # - ./mosquitto/config/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
    - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./mosquitto/log:/mosquitto/log
    - ./mosquitto/data/:/mosquitto/data
    restart: always
    networks:
      smart-bus-system-network:
        ipv4_address: 20.0.0.20
    ports:
      - 1883:1883

  
  # db:
  #   image: mysql
  #   container_name: se4iot-mysql
  #   # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
  #   # (this is just an example, not intended to be a production configuration)
  #   #command: --default-authentication-plugin=mysql_native_password --initialize-insecure
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #   ports:
  #   - "3306:3306" 
  #   volumes:
  #   - ./mysql-dump:/docker-entrypoint-initdb.d
  #   #- ./mysql-data:/var/lib/mysql


  # adminer:
  #   image: adminer
  #   container_name: se4iot-mysql-adminer
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - se4iot-net

  node-red:
    container_name: node-red
    build:
      context: ./nodered/
      dockerfile: Dockerfile
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Rome
      # - MYSQLUSERNAME=root
      # - MYSQLPASSWORD=example
      - MQTT_USERNAME=${IOT_USERNAME}
      - MQTT_PASSWORD=${IOT_PASSWORD}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
    ports:
      - "1880:1880"
    networks:
      smart-bus-system-network:
        ipv4_address: 20.0.0.30
    volumes:
      - ./nodered/data:/data
      - ./config.json:/system_data/config.json


  

  influxdb:
    container_name: smart-bus-system-influxdb
    image: influxdb:2.7.4
    ports:
      - 8086:8086
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${IOT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${IOT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=univaq
      - DOCKER_INFLUXDB_INIT_BUCKET=smart-bus-system
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks:
      smart-bus-system-network:
        ipv4_address: 20.0.0.40


  # telegraf:
  #   image: telegraf:latest
  #   container_name: telegraf
  #   depends_on:
  #     - influxdb
  #   restart: unless-stopped
  #   volumes:
  #     - ./telegraf/smart-bus-system-bucket.conf:/etc/telegraf/telegraf.conf:ro
  #     - ./telegraf/proc:/host/proc:ro
  #     - ./telegraf/sys:/host/sys:ro
  #     - ./telegraf/etc:/host/etc:ro
  #   environment:
  #     - INFLUX_TOKEN=_1YbZPbbIhEAVfKOlMNWXOjdyxHJFaM2PNUHF8j-0LqyB6QN9jN7ZUwmT8wH577bknUAuTpBmXQkKN8rLFXnWg==
  #     - HOST_PROC=/host/proc
  #     - HOST_SYS=/host/sys
  #     - HOST_ETC=/host/etc
  #   networks:
  #     smart-bus-system-network:
  #       ipv4_address: 20.0.0.60


  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: se4iot-rabbitmq
  #   ports:
  #     - "5672:5672"    # Port for RabbitMQ client connections
  #     - "15672:15672"  # Port for RabbitMQ management UI
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   networks:
  #     se4iot-network:
  #       ipv4_address: 20.0.0.105

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=volkovlabs-form-panel
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      smart-bus-system-network:
        ipv4_address: 20.0.0.50

  # openfire:
  #   container_name: se4iot-openfire
  #   build:
  #     context: ./openfire/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "9090:9090"
  #     - "9091:9091"
  #     - "5222:5222"
  #     - "5269:5269"
  #   networks:
  #     se4iot-network:
  #       ipv4_address: 20.0.0.106
  #   volumes:
  #     - ./openfire/data/conf:/opt/openfire/conf
  # #    - ./openfire/data/logs:/opt/openfire/logs
  #     - ./openfire/data/embedded-db:/opt/openfire/embedded-db
  #     - ./openfire/data/resources:/opt/openfire/resources
  # #    - ./openfire/data/plugins:/opt/openfire/plugins
  #   hostname: localhost 
  #   restart: unless-stopped
