networks:
  smart-bus-system-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK}.0/8


services:

  sensors:
    build: ./sensors
    depends_on:
      - mosquitto
      - config-api
      - grafana-middleware-api
    environment:
      - IOT_USERNAME=${IOT_USERNAME}
      - IOT_PASSWORD=${IOT_PASSWORD}
      - NETWORK=${NETWORK}
    container_name: smart-bus-system-sensors
    networks:
      smart-bus-system-network:
        ipv4_address: ${NETWORK}.10

  config-api:
    build: ./config-api
    volumes:
      - ./config-api/config.json:/usr/src/app/config.json
    container_name: smart-bus-system-config-api
    networks:
      smart-bus-system-network:
        ipv4_address: ${NETWORK}.12
    ports:
      - 5001:5001

  grafana-middleware-api:
    build: ./grafana-middleware-api
    container_name: smart-bus-system-grafana-middleware-api
    networks:
      smart-bus-system-network:
        ipv4_address: ${NETWORK}.11
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - NETWORK=${NETWORK}
    depends_on:
      - influxdb
      - config-api
    ports:
      - 5000:5000

  mosquitto:
    container_name: smart-bus-system-mosquitto
    build:
      context: ./mosquitto
      args:
        - IOT_USERNAME=${IOT_USERNAME}
        - IOT_PASSWORD=${IOT_PASSWORD}
    environment:
      - IOT_USERNAME=${IOT_USERNAME}
      - IOT_PASSWORD=${IOT_PASSWORD}
    volumes:
    - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./mosquitto/log:/mosquitto/log
    - ./mosquitto/data/:/mosquitto/data
    restart: always
    networks:
      smart-bus-system-network:
        ipv4_address: ${NETWORK}.20
    ports:
      - 1883:1883


  node-red:
    container_name: node-red
    depends_on:
      - mosquitto
      - influxdb
    build:
      context: ./nodered/
      dockerfile: Dockerfile
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Rome
      - MQTT_USERNAME=${IOT_USERNAME}
      - MQTT_PASSWORD=${IOT_PASSWORD}  
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - MQTT_IP=${NETWORK}.20
      - INFLUX_IP=http://${NETWORK}.40:8086
    ports:
      - "1880:1880"
    networks:
      smart-bus-system-network:
        ipv4_address: ${NETWORK}.30
    volumes:
      - ./nodered/data:/data


  

  influxdb:
    container_name: smart-bus-system-influxdb
    image: influxdb:2.7.4
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${IOT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${IOT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=univaq
      - DOCKER_INFLUXDB_INIT_BUCKET=smart
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}
    networks:
      smart-bus-system-network:
        ipv4_address: ${NETWORK}.40


  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
      - grafana-middleware-api
    environment:
      - GF_SECURITY_ADMIN_USER=admin # decoupled from env, can be changable from grafana GUI 
      - GF_SECURITY_ADMIN_PASSWORD=admin # ^
      - GF_INSTALL_PLUGINS=volkovlabs-form-panel,yesoreyeram-infinity-datasource
      - GF_PLUGINS_PREINSTALLED=volkovlabs-form-panel
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.mailersend.net:587
      - GF_SMTP_USER=${MAIL_LOGIN}
      - GF_SMTP_PASSWORD=${MAIL_KEY}
      - GF_SMTP_FROM_ADDRESS=${MAIL_LOGIN}
      - GF_SMTP_FROM_NAME=SmartBusSystem
      - GF_SMTP_STARTTLS_POLICY=MandatoryStartTLS
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      smart-bus-system-network:
        ipv4_address: ${NETWORK}.50 