apiVersion: 1
contactPoints:
  - orgId: 1
    name: Telegram Bot
    receivers:
      # --- EMAIL CONFIGURATION ---
      - uid: cffnb4lu46ccgc
        type: email
        settings:
          addresses: mail@test.com
          singleEmail: false
          subject: 'Bus Alert'
          message: |
            Alert Details:
            
            {{ range .Alerts }}
            🚌 Bus ID: {{ .Labels.id }}
            ⚠️ Message: {{ .Annotations.summary }}
            🕒 Time: {{ .StartsAt.Format "15:04:05" }}
            -----------------------
            {{ end }}
        disableResolveMessage: false

      # --- TELEGRAM CONFIGURATION ---
      - uid: effn9t84ga3ggd
        type: telegram
        settings:
          bottoken: 123456:ABC-DEF1234ghIkl
          chatid: "123456789"
          disable_notification: false
          disable_web_page_preview: false
          parse_mode: None
          protect_content: false
          message: |
            {{ range .Alerts }}
            🚨 Alert Details:
            {{ .Annotations.summary }}
            {{ end }}
        disableResolveMessage: false